// FR-H09: DESIGN.md asset library for user-level visual systems.
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { isAbsolute, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { QualityItem, ThemePack } from '../types.js';
import type { ReferenceDesignSystemContext } from './reference-style.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const DEFAULT_ASSETS_DIR = resolve(__dirname, 'assets');
export const DEFAULT_DESIGN_SYSTEM_ID = 'general';

const DEFAULT_DESIGN_MD = `# General Purpose Design System

## Design System Name
General Purpose Design System

## Applicable Scenarios
- General product pages, dashboards, reports, diagrams, posters, and presentation artifacts.
- Use when the user has not supplied a more specific DESIGN.md asset.

## Brand Colors / Palette
- Canvas: #ffffff
- Surface: #f8fafc
- Primary: #2563eb
- Accent: #14b8a6
- Text: #0f172a
- Muted text: #475569
- Border: #cbd5e1

## Font Stack
- Heading: Inter, ui-sans-serif, system-ui, sans-serif
- Body: Inter, ui-sans-serif, system-ui, sans-serif
- Mono: ui-monospace, SFMono-Regular, Menlo, monospace

## Type Scale
- Caption: 12px / 16px
- Body: 16px / 24px
- Section title: 24px / 32px
- Page title: 40px / 48px

## Spacing System
- Base unit: 8px
- Compact gap: 8px
- Standard gap: 16px
- Section gap: 32px
- Page margin: 48px
- Radius small: 4px
- Radius medium: 8px

## Component Library Path or Component Description
- Components are expressed as HTML/CSS classes generated by Claw Design.
- Use .cd-card for grouped content, .cd-button for primary actions, .cd-chip for status labels, and .cd-panel for dense information regions.
- Prefer CSS variables derived from this file over literal visual values.

## Layout Constraints
- Use an 8px spacing rhythm.
- Keep text blocks left aligned unless the artifact format requires centered title treatment.
- Limit cards to 8px border radius.
- Keep page sections visually distinct without nesting cards inside cards.
- Ensure responsive layouts keep text inside its parent container.

## Reference Examples
- A clean report page with white canvas, slate text, blue primary actions, teal highlights, 48px page margin, and compact 8px radius cards.
- A dashboard with dense panels, clear hierarchy, neutral surfaces, and restrained accents.

## Forbidden Rules
- Do not introduce unrelated color families outside the palette.
- Do not use viewport-scaled font sizes.
- Do not use decorative gradient blobs or one-note color themes.
- Do not use rounded text pills when a standard icon or simple label is clearer.
- Do not hardcode colors, fonts, spacing, or radius values that conflict with this file.
`;

export interface DesignAsset {
  id: string;
  name: string;
  content: string;
  source: 'built-in' | 'custom' | 'runtime';
  path?: string;
  tokens: DesignAssetTokens;
}

export interface DesignAssetTokens {
  colors: string[];
  fonts: string[];
  fontSizes: string[];
  spacing: string[];
  radius: string[];
  components: string[];
  layoutConstraints: string[];
  forbiddenRules: string[];
}

export interface DesignAssetValidationResult {
  valid: boolean;
  missing: string[];
  errors: string[];
}

export interface DesignAssetResolution {
  asset: DesignAsset;
  promptContext: string;
  generationConstraints: string[];
  qualityRules: QualityItem[];
  deliveryNotes: string[];
  gapMessage?: string;
}

export interface DesignAssetLibraryOptions {
  builtInAssetsDir?: string;
  userAssetsDir?: string;
  activeId?: string;
}

export class DesignAssetLibrary {
  private readonly builtInAssetsDir: string;
  private readonly userAssetsDir?: string;
  private activeId: string;

  constructor(options: DesignAssetLibraryOptions = {}) {
    this.builtInAssetsDir = options.builtInAssetsDir ?? DEFAULT_ASSETS_DIR;
    this.userAssetsDir = options.userAssetsDir;
    this.activeId = options.activeId ?? DEFAULT_DESIGN_SYSTEM_ID;
  }

  async list(): Promise<DesignAsset[]> {
    const builtInIds = await this.listBuiltInIds();
    const builtIns = await Promise.all(builtInIds.map(id => this.loadBuiltIn(id)));
    const custom = this.userAssetsDir ? await this.loadCustomAssets() : [];
    const seen = new Set<string>();
    return [...custom, ...builtIns].filter(asset => {
      if (seen.has(asset.id)) return false;
      seen.add(asset.id);
      return true;
    });
  }

  async get(id: string): Promise<DesignAsset | null> {
    this.assertSafeAssetId(id);
    if (this.userAssetsDir) {
      const custom = await this.loadAssetFromPath(id, this.resolveUserAssetPath(id), 'custom');
      if (custom) return custom;
    }
    if (id === DEFAULT_DESIGN_SYSTEM_ID) return this.loadBuiltIn(id);
    if (await this.builtInExists(id)) return this.loadBuiltIn(id);
    return null;
  }

  /**
   * Discover built-in asset ids from the assets directory. The default system
   * is always present (it has a hardcoded fallback even if the file is absent);
   * additional built-in presets are picked up from their <id>/DESIGN.md folders.
   */
  private async listBuiltInIds(): Promise<string[]> {
    const ids = new Set<string>([DEFAULT_DESIGN_SYSTEM_ID]);
    const entries = await readdir(this.builtInAssetsDir, { withFileTypes: true }).catch(() => []);
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      if (!this.isSafeAssetId(entry.name)) continue;
      if (await this.builtInExists(entry.name)) ids.add(entry.name);
    }
    return [...ids];
  }

  private async builtInExists(id: string): Promise<boolean> {
    if (!this.isSafeAssetId(id)) return false;
    const path = join(this.builtInAssetsDir, id, 'DESIGN.md');
    const content = await readFile(path, 'utf-8').catch(() => null);
    return Boolean(content && this.validate(content).valid);
  }

  async create(id: string, content: string): Promise<DesignAsset> {
    return this.save(id, content);
  }

  async save(id: string, content: string): Promise<DesignAsset> {
    if (!this.userAssetsDir) {
      throw new Error('Cannot save custom DESIGN.md because userAssetsDir was not configured.');
    }
    const validation = this.validate(content);
    if (!validation.valid) {
      throw new Error(`Invalid DESIGN.md: missing ${validation.missing.join(', ')}`);
    }
    const path = this.resolveUserAssetPath(id);
    const dir = resolve(path, '..');
    await mkdir(dir, { recursive: true });
    await writeFile(path, content, 'utf-8');
    return this.parseAsset(id, content, 'custom', path);
  }

  async select(id: string): Promise<DesignAsset> {
    const asset = await this.get(id);
    if (!asset) {
      throw new Error(`DESIGN.md asset "${id}" not found. Available: ${(await this.list()).map(a => a.id).join(', ')}`);
    }
    this.activeId = id;
    return asset;
  }

  async getActive(): Promise<DesignAsset> {
    return (await this.get(this.activeId)) ?? this.loadBuiltIn(DEFAULT_DESIGN_SYSTEM_ID);
  }

  async resolveForSkill(skillName: string, context: Record<string, unknown> = {}): Promise<DesignAssetResolution> {
    const requested = this.getRequestedDesignSystem(context) ?? await this.readSkillDesignSystem(skillName);
    let asset = requested ? await this.get(requested) : await this.getActive();
    let gapMessage: string | undefined;

    if (!asset) {
      gapMessage = `DESIGN.md asset "${requested}" was requested by SKILL.md or task context but was not found; using "${DEFAULT_DESIGN_SYSTEM_ID}" instead.`;
      asset = await this.loadBuiltIn(DEFAULT_DESIGN_SYSTEM_ID);
    }

    const referenceOverlay = this.getReferenceStyleDesignMd(context);
    if (referenceOverlay) {
      asset = this.mergeReferenceOverlay(asset, referenceOverlay);
    }

    return {
      asset,
      promptContext: this.toPromptContext(asset),
      generationConstraints: this.toGenerationConstraints(asset),
      qualityRules: this.toQualityRules(asset, gapMessage),
      deliveryNotes: this.toDeliveryNotes(asset, gapMessage),
      gapMessage,
    };
  }

  toReferenceDesignSystemContext(asset: DesignAsset): ReferenceDesignSystemContext {
    return {
      id: asset.id,
      name: asset.name,
      source: asset.source,
      content: asset.content,
      tokens: asset.tokens,
      generationConstraints: this.toGenerationConstraints(asset),
      deliveryNotes: this.toDeliveryNotes(asset),
    };
  }

  validate(content: string): DesignAssetValidationResult {
    const required: Array<[string, RegExp]> = [
      ['design system name', /design system name|^#\s+.+/im],
      ['applicable scenarios', /applicable scenarios?/i],
      ['brand colors or palette', /brand colors?|palette/i],
      ['font stack', /font stack/i],
      ['type scale', /type scale|font size|字号/i],
      ['spacing system', /spacing system|spacing/i],
      ['component library path or component description', /component library path|component description|components?/i],
      ['layout constraints', /layout constraints?/i],
      ['reference examples', /reference examples?|参考样例/i],
      ['forbidden rules', /forbidden rules?|禁用规则/i],
    ];
    const missing = required.filter(([, re]) => !re.test(content)).map(([name]) => name);
    return {
      valid: missing.length === 0,
      missing,
      errors: missing.map(name => `Missing ${name}`),
    };
  }

  toThemePack(asset: DesignAsset, fallback: ThemePack): ThemePack {
    const [canvas, surface, primary, accent, text] = asset.tokens.colors;
    const heading = asset.tokens.fonts[0] ?? fallback.fontHeading;
    const body = asset.tokens.fonts[1] ?? heading;
    const spacing = asset.tokens.spacing[0] ?? fallback.spacingUnit;
    const radius = asset.tokens.radius[0] ?? fallback.radius;
    return {
      ...fallback,
      colorPrimary: primary ?? accent ?? fallback.colorPrimary,
      colorBg: canvas ?? surface ?? fallback.colorBg,
      fontHeading: heading,
      fontBody: body,
      spacingUnit: spacing,
      radius,
      cssVariables: {
        ...fallback.cssVariables,
        '--cd-color-bg': canvas ?? surface ?? fallback.colorBg,
        '--cd-color-surface': surface ?? canvas ?? fallback.colorBg,
        '--cd-color-primary': primary ?? fallback.colorPrimary,
        '--cd-color-accent': accent ?? primary ?? fallback.colorPrimary,
        '--cd-color-text': text ?? '#0f172a',
        '--cd-font-heading': heading,
        '--cd-font-body': body,
        '--cd-spacing-unit': spacing,
        '--cd-radius': radius,
      },
      baselineLabel: asset.name,
    };
  }

  checkHtml(html: string, asset: DesignAsset, taskId: string): QualityItem[] {
    const items: QualityItem[] = [];
    const allowedColors = new Set(asset.tokens.colors.map(c => c.toLowerCase()));
    const colorViolations = new Set<string>();
    for (const color of html.match(/#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{3})\b/g) ?? []) {
      if (!allowedColors.has(color.toLowerCase())) {
        colorViolations.add(color);
        items.push({
          rule: 'design-md:color-palette',
          passed: false,
          severity: 'warn',
          message: `HTML uses color ${color} outside current DESIGN.md palette for task ${taskId}.`,
        });
      }
    }

    if (colorViolations.size === 0) {
      items.push({
        rule: 'design-md:color-palette',
        passed: true,
        severity: 'info',
        message: `HTML colors follow the current DESIGN.md palette for task ${taskId}.`,
      });
    }

    items.push(...this.checkFontFamilies(html, asset, taskId));
    items.push(...this.checkSpacingAndRadius(html, asset, taskId));
    items.push(...this.checkComponentClasses(html, asset, taskId));
    items.push(...this.checkLayoutConstraints(html, asset, taskId));
    return items;
  }

  private async loadBuiltIn(id: string): Promise<DesignAsset> {
    const path = join(this.builtInAssetsDir, id, 'DESIGN.md');
    const content = await readFile(path, 'utf-8').catch(() => DEFAULT_DESIGN_MD);
    return this.parseAsset(id, content, 'built-in', path);
  }

  private async loadCustomAssets(): Promise<DesignAsset[]> {
    if (!this.userAssetsDir) return [];
    const entries = await readdir(this.userAssetsDir).catch(() => []);
    const safeEntries = entries.filter(id => this.isSafeAssetId(id));
    const assets = await Promise.all(safeEntries.map(id => this.loadAssetFromPath(id, this.resolveUserAssetPath(id), 'custom')));
    return assets.filter((asset): asset is DesignAsset => Boolean(asset));
  }

  private assertSafeAssetId(id: string): void {
    if (!this.isSafeAssetId(id)) {
      throw new Error(`Invalid DESIGN.md asset id "${id}". Use a slug without "..", absolute paths, whitespace, or path separators.`);
    }
  }

  private isSafeAssetId(id: string): boolean {
    return /^[a-z0-9][a-z0-9._-]*$/i.test(id) && !id.includes('..') && !id.includes('/') && !id.includes('\\') && !isAbsolute(id);
  }

  private mergeReferenceOverlay(base: DesignAsset, referenceOverlay: string): DesignAsset {
    const overlayTokens = this.extractTokens(referenceOverlay);
    const overlayColors = overlayTokens.colors.length > 0 ? overlayTokens.colors : base.tokens.colors;
    return {
      ...base,
      id: `${base.id}-reference-overlay`,
      name: `${base.name} + Reference Image Style Overlay`,
      content: [
        referenceOverlay,
        '',
        '---',
        '',
        '# Base DESIGN.md Context',
        '',
        base.content,
      ].join('\n'),
      source: 'runtime',
      tokens: {
        ...base.tokens,
        colors: overlayColors,
        layoutConstraints: [...overlayTokens.layoutConstraints, ...base.tokens.layoutConstraints],
        forbiddenRules: [...overlayTokens.forbiddenRules, ...base.tokens.forbiddenRules],
      },
    };
  }

  private resolveUserAssetPath(id: string): string {
    this.assertSafeAssetId(id);
    if (!this.userAssetsDir) {
      throw new Error('Cannot resolve custom DESIGN.md because userAssetsDir was not configured.');
    }
    const base = resolve(this.userAssetsDir);
    const path = resolve(base, id, 'DESIGN.md');
    const rel = relative(base, path);
    if (rel.startsWith('..') || isAbsolute(rel) || path === base || !path.startsWith(`${base}${sep}`)) {
      throw new Error(`Invalid DESIGN.md asset id "${id}". Resolved path escapes the user asset directory.`);
    }
    return path;
  }

  private checkFontFamilies(html: string, asset: DesignAsset, taskId: string): QualityItem[] {
    const allowedFonts = new Set(asset.tokens.fonts.flatMap(stack => this.parseFontStack(stack)));
    const families = Array.from(html.matchAll(/font-family\s*:\s*([^;"'}]+)/gi)).map(match => match[1]?.trim() ?? '').filter(Boolean);
    const invalid = families.filter(family => {
      const requested = this.parseFontStack(family);
      return requested.length > 0 && requested.every(font => !allowedFonts.has(font));
    });

    if (invalid.length === 0) {
      return [{
        rule: 'design-md:font-stack',
        passed: true,
        severity: 'info',
        message: `HTML font families follow the current DESIGN.md font stack for task ${taskId}.`,
      }];
    }

    return invalid.map(family => ({
      rule: 'design-md:font-stack',
      passed: false,
      severity: 'warn',
      message: `HTML uses font family "${family}" outside current DESIGN.md font stack for task ${taskId}.`,
    }));
  }

  private checkSpacingAndRadius(html: string, asset: DesignAsset, taskId: string): QualityItem[] {
    const allowed = new Set([...asset.tokens.spacing, ...asset.tokens.radius].map(value => value.toLowerCase()));
    const values = Array.from(html.matchAll(/\b(?:margin|padding|gap|row-gap|column-gap|border-radius)\s*:\s*([^;"}]+)/gi))
      .flatMap(match => match[1]?.match(/\b\d+(?:\.\d+)?px\b/g) ?? []);
    const invalid = values.filter(value => !allowed.has(value.toLowerCase()));

    if (invalid.length === 0) {
      return [{
        rule: 'design-md:spacing-rhythm',
        passed: true,
        severity: 'info',
        message: `HTML spacing and radius values follow the current DESIGN.md rhythm for task ${taskId}.`,
      }];
    }

    return Array.from(new Set(invalid)).map(value => ({
      rule: 'design-md:spacing-rhythm',
      passed: false,
      severity: 'warn',
      message: `HTML uses spacing/radius value ${value} outside current DESIGN.md spacing system for task ${taskId}.`,
    }));
  }

  private checkComponentClasses(html: string, asset: DesignAsset, taskId: string): QualityItem[] {
    const allowedComponents = new Set(asset.tokens.components.flatMap(line => line.match(/\.cd-[a-z0-9_-]+/gi) ?? []).map(name => name.slice(1).toLowerCase()));
    const cdClasses = Array.from(html.matchAll(/class\s*=\s*["']([^"']+)["']/gi))
      .flatMap(match => (match[1] ?? '').split(/\s+/))
      .filter(name => /^cd-/i.test(name));
    const invalid = cdClasses.filter(name => !allowedComponents.has(name.toLowerCase()));

    if (invalid.length === 0) {
      return [{
        rule: 'design-md:component-library',
        passed: true,
        severity: 'info',
        message: `HTML component classes follow the current DESIGN.md component guidance for task ${taskId}.`,
      }];
    }

    return Array.from(new Set(invalid)).map(name => ({
      rule: 'design-md:component-library',
      passed: false,
      severity: 'warn',
      message: `HTML uses component class ".${name}" outside current DESIGN.md component guidance for task ${taskId}.`,
    }));
  }

  private checkLayoutConstraints(html: string, asset: DesignAsset, taskId: string): QualityItem[] {
    const rules = [...asset.tokens.layoutConstraints, ...asset.tokens.forbiddenRules].join('\n').toLowerCase();
    const violations: QualityItem[] = [];

    if (/viewport-scaled font sizes|scale fonts with viewport width/.test(rules) && /\b\d+(?:\.\d+)?vw\b/i.test(html)) {
      violations.push({
        rule: 'design-md:layout-constraints',
        passed: false,
        severity: 'warn',
        message: `HTML uses viewport-scaled font sizing, which current DESIGN.md forbids for task ${taskId}.`,
      });
    }
    if (/nesting cards inside cards|cards inside cards/.test(rules) && /class\s*=\s*["'][^"']*\bcd-card\b[^"']*["'][\s\S]*class\s*=\s*["'][^"']*\bcd-card\b/i.test(html)) {
      violations.push({
        rule: 'design-md:layout-constraints',
        passed: false,
        severity: 'warn',
        message: `HTML appears to nest .cd-card components, which current DESIGN.md forbids for task ${taskId}.`,
      });
    }
    if (/gradient blobs|decorative gradient/.test(rules) && /radial-gradient|linear-gradient/i.test(html)) {
      violations.push({
        rule: 'design-md:layout-constraints',
        passed: false,
        severity: 'warn',
        message: `HTML uses decorative gradients that current DESIGN.md forbids for task ${taskId}.`,
      });
    }

    if (violations.length > 0) return violations;
    return [{
      rule: 'design-md:layout-constraints',
      passed: true,
      severity: 'info',
      message: `HTML layout constraints and forbidden rules were checked against current DESIGN.md for task ${taskId}.`,
    }];
  }

  private parseFontStack(stack: string): string[] {
    return stack
      .split(',')
      .map(font => font.trim().replace(/^['"]|['"]$/g, '').toLowerCase())
      .filter(Boolean);
  }

  private async loadAssetFromPath(id: string, path: string, source: DesignAsset['source']): Promise<DesignAsset | null> {
    const content = await readFile(path, 'utf-8').catch(() => null);
    if (!content) return null;
    const validation = this.validate(content);
    if (!validation.valid) return null;
    return this.parseAsset(id, content, source, path);
  }

  private parseAsset(id: string, content: string, source: DesignAsset['source'], path?: string): DesignAsset {
    const tokens = this.extractTokens(content);
    return {
      id,
      name: this.extractLine(content, /design system name/i) ?? content.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? id,
      content,
      source,
      path,
      tokens,
    };
  }

  private extractTokens(content: string): DesignAssetTokens {
    return {
      colors: Array.from(new Set(content.match(/#(?:[0-9a-fA-F]{6}|[0-9a-fA-F]{3})\b/g) ?? [])),
      fonts: Array.from(new Set((content.match(/(?:Heading|Body|Mono):\s*([^\n]+)/gi) ?? []).map(line => line.split(':').slice(1).join(':').trim()))),
      fontSizes: Array.from(new Set(content.match(/\b\d+(?:\.\d+)?px\s*\/\s*\d+(?:\.\d+)?px\b/g) ?? [])),
      spacing: Array.from(new Set(content.match(/\b\d+(?:\.\d+)?px\b/g) ?? [])),
      radius: Array.from(new Set((content.match(/radius[^:\n]*:\s*\d+(?:\.\d+)?px/gi) ?? []).map(line => line.match(/\d+(?:\.\d+)?px/)?.[0] ?? '').filter(Boolean))),
      components: this.extractSectionLines(content, /component library path|component description/i),
      layoutConstraints: this.extractSectionLines(content, /layout constraints/i),
      forbiddenRules: this.extractSectionLines(content, /forbidden rules/i),
    };
  }

  private toPromptContext(asset: DesignAsset): string {
    return [
      '## DESIGN.md Asset Context',
      `Design system: ${asset.name} (${asset.id}, ${asset.source})`,
      '',
      asset.content,
    ].join('\n');
  }

  private toGenerationConstraints(asset: DesignAsset): string[] {
    return [
      `Use DESIGN.md "${asset.name}" as the visual source of truth.`,
      `Use only these palette colors unless content semantics require a documented exception: ${asset.tokens.colors.join(', ')}`,
      `Use these font stacks: ${asset.tokens.fonts.join(' | ')}`,
      `Use spacing/radius values from DESIGN.md: ${asset.tokens.spacing.join(', ')}`,
      ...asset.tokens.layoutConstraints,
      ...asset.tokens.forbiddenRules.map(rule => `Forbidden: ${rule}`),
    ].filter(Boolean);
  }

  private toQualityRules(asset: DesignAsset, gapMessage?: string): QualityItem[] {
    const rules: QualityItem[] = [
      {
        rule: 'design-md:loaded',
        passed: true,
        severity: 'info',
        message: `Loaded DESIGN.md asset "${asset.id}" (${asset.source}).`,
      },
    ];
    if (gapMessage) {
      rules.push({ rule: 'design-md:fallback', passed: false, severity: 'warn', message: gapMessage });
    }
    return rules;
  }

  private toDeliveryNotes(asset: DesignAsset, gapMessage?: string): string[] {
    return [
      `DESIGN.md: ${asset.name} (${asset.id})`,
      `Palette: ${asset.tokens.colors.join(', ')}`,
      `Typography: ${asset.tokens.fonts.join(' | ')}`,
      ...(gapMessage ? [gapMessage] : []),
    ];
  }

  private getRequestedDesignSystem(context: Record<string, unknown>): string | null {
    const value = context.designSystemId ?? context.designSystem ?? context.designAssetId;
    return typeof value === 'string' && value.trim() ? value.trim() : null;
  }

  private getReferenceStyleDesignMd(context: Record<string, unknown>): string | null {
    const value = context.referenceStyleDesignMd;
    return typeof value === 'string' && value.trim() ? value.trim() : null;
  }

  private async readSkillDesignSystem(skillName: string): Promise<string | null> {
    const skillDir = this.skillNameToDir(skillName);
    const skillPath = resolve(__dirname, '../../skill', skillDir, 'SKILL.md');
    const content = await readFile(skillPath, 'utf-8').catch(() => null);
    if (!content) return null;
    const frontmatter = content.match(/^---\n([\s\S]*?)\n---/);
    const source = frontmatter?.[1] ?? content;
    const match = source.match(/^designSystem:\s*([^\n]+)$/m) ?? source.match(/^design-system:\s*([^\n]+)$/m);
    return match?.[1]?.trim() ?? null;
  }

  private skillNameToDir(skillName: string): string {
    const map: Record<string, string> = {
      chart: 'charts',
      'arch-diagram': 'architecture',
      'ui-mockup': 'mockup',
    };
    return map[skillName] ?? skillName;
  }

  private extractLine(content: string, heading: RegExp): string | null {
    const lines = content.split('\n');
    const index = lines.findIndex(line => heading.test(line));
    if (index < 0) return null;
    for (const line of lines.slice(index + 1)) {
      const trimmed = line.replace(/^[-*]\s*/, '').trim();
      if (trimmed) return trimmed;
    }
    return null;
  }

  private extractSectionLines(content: string, heading: RegExp): string[] {
    const lines = content.split('\n');
    const index = lines.findIndex(line => /^##\s+/.test(line) && heading.test(line));
    if (index < 0) return [];
    const result: string[] = [];
    for (const line of lines.slice(index + 1)) {
      if (/^##\s+/.test(line)) break;
      const trimmed = line.replace(/^[-*]\s*/, '').trim();
      if (trimmed) result.push(trimmed);
    }
    return result;
  }
}
